import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";
import type { Asset, AssetConfig, AssetKind, TargetConfig, TargetName } from "./schema.ts";
import { KINDS, TARGETS } from "./schema.ts";
import { assertNoProtectedFrontmatter } from "./frontmatter.ts";
import { copyDir, listFiles, pathExists, resetDir, writeFileEnsured } from "./fs.ts";
import { renderOpenCode } from "./renderers/opencode.ts";
import { renderPi } from "./renderers/pi.ts";
import { renderClaude } from "./renderers/claude.ts";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_DIR = path.join(REPO_ROOT, "source");
const OUTPUT_DIRS = [".opencode", ".pi", ".claude"];

interface RenderedFile {
  path: string;
  content: string;
  asset: Asset;
  extrasDir?: string;
}

function assertInsideRepo(target: string): void {
  const relative = path.relative(REPO_ROOT, target);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`Refusing to operate outside repo: ${target}`);
  }
}

function assertKnownOutputDir(dir: string): void {
  if (!OUTPUT_DIRS.includes(dir)) throw new Error(`Refusing to reset unknown output dir: ${dir}`);
  assertInsideRepo(path.join(REPO_ROOT, dir));
}

async function discoverAssets(): Promise<Asset[]> {
  const assets: Asset[] = [];
  const seen = new Set<string>();

  for (const kind of KINDS) {
    const root = path.join(SOURCE_DIR, `${kind}s`);
    if (!(await pathExists(root))) continue;
    const entries = await fs.readdir(root, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const id = entry.name;
      const dir = path.join(root, id);
      const configPath = path.join(dir, "asset.yaml");
      const bodyPath = path.join(dir, "body.md");
      if (!(await pathExists(configPath))) throw new Error(`${path.relative(REPO_ROOT, dir)} is missing asset.yaml`);
      if (!(await pathExists(bodyPath))) throw new Error(`${path.relative(REPO_ROOT, dir)} is missing body.md`);

      const config = YAML.parse(await fs.readFile(configPath, "utf8")) as AssetConfig;
      if (!config || config.kind !== kind) throw new Error(`${path.relative(REPO_ROOT, configPath)} must set kind: ${kind}`);
      if (!config.targets || typeof config.targets !== "object") throw new Error(`${path.relative(REPO_ROOT, configPath)} must define targets`);
      for (const target of Object.keys(config.targets)) {
        if (!TARGETS.includes(target as TargetName)) throw new Error(`${path.relative(REPO_ROOT, configPath)} has unknown target: ${target}`);
      }
      assertNoProtectedFrontmatter(config.frontmatter, `${kind}:${id}:shared`);
      for (const target of TARGETS) {
        const targetConfig = config.targets[target];
        if (targetConfig) assertNoProtectedFrontmatter(targetConfig.frontmatter, `${kind}:${id}:${target}`);
      }

      const assetKey = `${kind}:${id}`;
      if (seen.has(assetKey)) throw new Error(`Duplicate asset: ${assetKey}`);
      seen.add(assetKey);

      const body = await fs.readFile(bodyPath, "utf8");
      const extras = (await listFiles(dir)).filter((file) => {
        const base = path.basename(file);
        return base !== "asset.yaml" && base !== "body.md";
      });

      assets.push({ id, kind, dir, bodyPath, body, config, extras });
    }
  }

  return assets.sort((a, b) => `${a.kind}:${a.id}`.localeCompare(`${b.kind}:${b.id}`));
}

function renderForTarget(asset: Asset, target: TargetName, config: TargetConfig): RenderedFile[] {
  const rendered =
    target === "opencode" ? renderOpenCode(asset, config) : target === "pi" ? renderPi(asset, config) : renderClaude(asset, config);
  return rendered.map((item) => ({ ...item, asset }));
}

function renderAssets(assets: Asset[]): RenderedFile[] {
  const files: RenderedFile[] = [];
  const byPath = new Map<string, string>();

  for (const asset of assets) {
    for (const target of TARGETS) {
      const targetConfig = asset.config.targets[target];
      if (!targetConfig) continue;
      const rendered = renderForTarget(asset, target, targetConfig);
      for (const file of rendered) {
        const previous = byPath.get(file.path);
        if (previous) throw new Error(`Output path collision: ${file.path} generated by both ${previous} and ${asset.kind}:${asset.id}`);
        byPath.set(file.path, `${asset.kind}:${asset.id}`);
        files.push(file);
      }
    }
  }

  return files.sort((a, b) => a.path.localeCompare(b.path));
}

async function copyHarnesses(outputRoot: string): Promise<void> {
  for (const dir of OUTPUT_DIRS) {
    const name = dir.slice(1);
    await copyDir(path.join(SOURCE_DIR, "harnesses", name), path.join(outputRoot, dir));
  }
}

async function copyExtras(file: RenderedFile, outputRoot: string): Promise<void> {
  if (!file.extrasDir || file.asset.extras.length === 0) return;
  for (const extra of file.asset.extras) {
    const relative = path.relative(file.asset.dir, extra);
    await copyDirOrFile(extra, path.join(outputRoot, file.extrasDir, relative));
  }
}

async function copyDirOrFile(src: string, dest: string): Promise<void> {
  const stat = await fs.lstat(src);
  if (stat.isDirectory()) await copyDir(src, dest);
  else if (stat.isFile()) await writeFileEnsured(dest, await fs.readFile(src, "utf8"));
}

async function writeRendered(outputRoot: string, files: RenderedFile[]): Promise<void> {
  for (const file of files) {
    await writeFileEnsured(path.join(outputRoot, file.path), file.content);
    await copyExtras(file, outputRoot);
  }
}

async function generateTo(outputRoot: string, resetOutputs: boolean): Promise<void> {
  if (resetOutputs) {
    for (const dir of OUTPUT_DIRS) {
      assertKnownOutputDir(dir);
      await resetDir(path.join(outputRoot, dir));
    }
  } else {
    for (const dir of OUTPUT_DIRS) await resetDir(path.join(outputRoot, dir));
  }

  await copyHarnesses(outputRoot);
  const assets = await discoverAssets();
  await writeRendered(outputRoot, renderAssets(assets));
}

async function compareDirs(actualRoot: string, expectedRoot: string): Promise<string[]> {
  const diffs: string[] = [];
  for (const dir of OUTPUT_DIRS) {
    const actualFiles = (await listFiles(path.join(actualRoot, dir))).map((file) => path.relative(actualRoot, file));
    const expectedFiles = (await listFiles(path.join(expectedRoot, dir))).map((file) => path.relative(expectedRoot, file));
    const names = [...new Set([...actualFiles, ...expectedFiles])].sort();
    for (const name of names) {
      const actual = actualFiles.includes(name);
      const expected = expectedFiles.includes(name);
      if (!actual) {
        diffs.push(`missing generated file: ${name}`);
        continue;
      }
      if (!expected) {
        diffs.push(`extra generated file: ${name}`);
        continue;
      }
      const [actualContent, expectedContent] = await Promise.all([
        fs.readFile(path.join(actualRoot, name), "utf8"),
        fs.readFile(path.join(expectedRoot, name), "utf8"),
      ]);
      if (actualContent !== expectedContent) diffs.push(`stale generated file: ${name}`);
    }
  }
  return diffs;
}

async function check(): Promise<void> {
  const tmp = await fs.mkdtemp(path.join(os.tmpdir(), "coding-harness-config-"));
  try {
    await generateTo(tmp, false);
    const diffs = await compareDirs(REPO_ROOT, tmp);
    if (diffs.length > 0) {
      console.error("Generated outputs are stale. Run pnpm run generate.\n");
      for (const diff of diffs) console.error(`- ${diff}`);
      process.exitCode = 1;
    }
  } finally {
    await fs.rm(tmp, { recursive: true, force: true });
  }
}

async function main(): Promise<void> {
  const command = process.argv[2];
  if (command === "generate") {
    await generateTo(REPO_ROOT, true);
    return;
  }
  if (command === "check") {
    await check();
    return;
  }
  throw new Error(`Usage: pnpm run generate | pnpm run check`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
